# Generated by Django 4.2 on 2023-06-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('head_0', models.CharField(default='', max_length=100)),
                ('content_0', models.CharField(default='', max_length=10000)),
                ('head_1', models.CharField(default='', max_length=100)),
                ('content_1', models.CharField(default='', max_length=10000)),
                ('head_2', models.CharField(default='', max_length=100)),
                ('content_2', models.CharField(default='', max_length=10000)),
                ('publish_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/thumbnail')),
                ('image_0', models.ImageField(default='', upload_to='blog/images')),
                ('image_1', models.ImageField(default='', upload_to='blog/images')),
                ('image_2', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
