# Generated by Django 4.2 on 2023-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Mmsg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Mname', models.CharField(max_length=50)),
                ('Memail', models.CharField(max_length=50)),
                ('Mphone', models.IntegerField(default='')),
                ('Mdesc', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
