# Generated by Django 4.2 on 2023-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Morder_id', models.AutoField(primary_key=True, serialize=False)),
                ('Mitems_json', models.CharField(max_length=5000)),
                ('Mname', models.CharField(max_length=100)),
                ('Memail', models.EmailField(max_length=100)),
                ('Maddress', models.CharField(max_length=1000)),
                ('Mcity', models.CharField(max_length=500)),
                ('Mstate', models.CharField(max_length=500)),
                ('Mzip_code', models.IntegerField(max_length=8)),
                ('Mphone', models.IntegerField(max_length=12)),
            ],
        ),
    ]
