# Generated by Django 4.2 on 2023-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Mphone',
            field=models.IntegerField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Mzip_code',
            field=models.IntegerField(default='', max_length=8),
        ),
    ]
