# Generated by Django 4.2 on 2023-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Mamount',
            field=models.IntegerField(default=1),
        ),
    ]
